FROM python:3.13.5

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app/src

COPY requirements.txt .

RUN pip install \
    --no-cache-dir \
    -r requirements.txt

COPY . .

EXPOSE 8501

CMD [
    "streamlit",
    "run",
    "src/financial_ai/ui/streamlit_app.py",
    "--server.address=0.0.0.0",
    "--server.port=8501"
]