FROM python:3.13.15

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app/src

COPY requirements.txt .

RUN pip install \
    --no-cache-dir \
    -r requirements.txt

COPY . .

EXPOSE 8000

CMD [
    "uvicorn",
    "financial_ai.api.main:app",
    "--host",
    "0.0.0.0",
    "--port",
    "8000"
]