apiVersion: v1
kind: Service

metadata:
  name: financial-ai-streamlit

spec:

  selector:
    app: financial-ai-streamlit

  ports:
    - port: {{ .Values.streamlit.service.port }}
      targetPort: 8501

  type: {{ .Values.streamlit.service.type }}